name: maasters
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  bloc: ^8.1.1
  cloud_firestore: ^5.6.0
  dartz: ^0.10.1
  dio: ^5.1.2
  firebase_auth: ^5.3.4
  firebase_core: ^3.9.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_localizations:
    sdk: flutter
  formz: ^0.8.0
  freezed_annotation: ^2.2.0
  get_it: ^8.0.3
  intl: ^0.19.0
  json_annotation: ^4.7.0

dev_dependencies:
  bloc_test: ^9.1.1
  build_runner: ^2.3.0
  flutter_test:
    sdk: flutter
  freezed: ^2.2.0
  json_serializable: ^6.5.4
  mocktail: ^1.0.4
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
  generate: true
  
  assets:
    # - assets/images/
    - assets/icons/
