import 'package:auth/auth.dart';
import 'package:flutter/material.dart';
import 'package:maasters/l10n/l10n.dart';

extension CountryTranslations on Countries {
  String translatedCountry(BuildContext context) {
    switch (this) {
      case Countries.arg:
        return context.l10n.arg;
      case Countries.alb:
        return context.l10n.alb;
      case Countries.ger:
        return context.l10n.ger;
      case Countries.and:
        return context.l10n.and;
      case Countries.ang:
        return context.l10n.ago;
      case Countries.antBar:
        return context.l10n.atg;
      case Countries.sau:
        return context.l10n.sau;
      case Countries.alg:
        return context.l10n.dza;
      case Countries.arm:
        return context.l10n.arm;
      case Countries.aus:
        return context.l10n.aus;
      case Countries.aut:
        return context.l10n.aut;
      case Countries.aze:
        return context.l10n.aze;
      case Countries.bah:
        return context.l10n.bhs;
      case Countries.ban:
        return context.l10n.bgd;
      case Countries.bar:
        return context.l10n.brb;
      case Countries.bhr:
        return context.l10n.bhr;
      case Countries.bel:
        return context.l10n.bel;
      case Countries.blz:
        return context.l10n.blz;
      case Countries.ben:
        return context.l10n.ben;
      case Countries.blr:
        return context.l10n.blr;
      case Countries.bir:
        return context.l10n.bir;
      case Countries.bol:
        return context.l10n.bol;
      case Countries.bosHer:
        return context.l10n.bih;
      case Countries.bot:
        return context.l10n.bwa;
      case Countries.bra:
        return context.l10n.bra;
      case Countries.bru:
        return context.l10n.brn;
      case Countries.bul:
        return context.l10n.bgr;
      case Countries.burFas:
        return context.l10n.bfa;
      case Countries.bur:
        return context.l10n.bur;
      case Countries.but:
        return context.l10n.but;
      case Countries.cpv:
        return context.l10n.cpv;
      case Countries.cam:
        return context.l10n.khm;
      case Countries.cmr:
        return context.l10n.cmr;
      case Countries.can:
        return context.l10n.can;
      case Countries.qat:
        return context.l10n.qat;
      case Countries.cha:
        return context.l10n.tcd;
      case Countries.chi:
        return context.l10n.chl;
      case Countries.chn:
        return context.l10n.chn;
      case Countries.cyp:
        return context.l10n.cyp;
      case Countries.vat:
        return context.l10n.vat;
      case Countries.col:
        return context.l10n.col;
      case Countries.com:
        return context.l10n.com;
      case Countries.norCor:
        return context.l10n.prk;
      case Countries.surCor:
        return context.l10n.kor;
      case Countries.cosMar:
        return context.l10n.civ;
      case Countries.cosRic:
        return context.l10n.cri;
      case Countries.cro:
        return context.l10n.hrv;
      case Countries.cub:
        return context.l10n.cub;
      case Countries.den:
        return context.l10n.dnk;
      case Countries.dma:
        return context.l10n.dma;
      case Countries.ecu:
        return context.l10n.ecu;
      case Countries.egy:
        return context.l10n.egy;
      case Countries.slv:
        return context.l10n.slv;
      case Countries.uae:
        return context.l10n.are;
      case Countries.eri:
        return context.l10n.eri;
      case Countries.slo:
        return context.l10n.svk;
      case Countries.slov:
        return context.l10n.svn;
      case Countries.esp:
        return context.l10n.esp;
      case Countries.usa:
        return context.l10n.usa;
      case Countries.est:
        return context.l10n.est;
      case Countries.esw:
        return context.l10n.swz;
      case Countries.eth:
        return context.l10n.eth;
      case Countries.phi:
        return context.l10n.phl;
      case Countries.fin:
        return context.l10n.fin;
      case Countries.fij:
        return context.l10n.fji;
      case Countries.fra:
        return context.l10n.fra;
      case Countries.gab:
        return context.l10n.gab;
      case Countries.gam:
        return context.l10n.gmb;
      case Countries.geo:
        return context.l10n.geo;
      case Countries.gha:
        return context.l10n.gha;
      case Countries.grd:
        return context.l10n.grd;
      case Countries.gre:
        return context.l10n.grc;
      case Countries.gua:
        return context.l10n.gtm;
      case Countries.guy:
        return context.l10n.guy;
      case Countries.gin:
        return context.l10n.gin;
      case Countries.guiBis:
        return context.l10n.gnb;
      case Countries.guiEcu:
        return context.l10n.gnq;
      case Countries.hai:
        return context.l10n.hti;
      case Countries.hon:
        return context.l10n.hnd;
      case Countries.hun:
        return context.l10n.hun;
      case Countries.ind:
        return context.l10n.ind;
      case Countries.idn:
        return context.l10n.idn;
      case Countries.irq:
        return context.l10n.irq;
      case Countries.irn:
        return context.l10n.irn;
      case Countries.irl:
        return context.l10n.irl;
      case Countries.isl:
        return context.l10n.isl;
      case Countries.mhl:
        return context.l10n.mhl;
      case Countries.slb:
        return context.l10n.slb;
      case Countries.isr:
        return context.l10n.isr;
      case Countries.ita:
        return context.l10n.ita;
      case Countries.jam:
        return context.l10n.jam;
      case Countries.jap:
        return context.l10n.jpn;
      case Countries.jor:
        return context.l10n.jor;
      case Countries.kaz:
        return context.l10n.kaz;
      case Countries.ken:
        return context.l10n.ken;
      case Countries.kgz:
        return context.l10n.kgz;
      case Countries.kir:
        return context.l10n.kir;
      case Countries.kwt:
        return context.l10n.kwt;
      case Countries.lao:
        return context.l10n.lao;
      case Countries.les:
        return context.l10n.lso;
      case Countries.lva:
        return context.l10n.lva;
      case Countries.lbn:
        return context.l10n.lbn;
      case Countries.lbr:
        return context.l10n.lbr;
      case Countries.lby:
        return context.l10n.lby;
      case Countries.lie:
        return context.l10n.lie;
      case Countries.ltu:
        return context.l10n.ltu;
      case Countries.lux:
        return context.l10n.lux;
      case Countries.mad:
        return context.l10n.mdg;
      case Countries.mys:
        return context.l10n.mys;
      case Countries.mwi:
        return context.l10n.mwi;
      case Countries.mdv:
        return context.l10n.mdv;
      case Countries.mli:
        return context.l10n.mli;
      case Countries.mlt:
        return context.l10n.mlt;
      case Countries.mar:
        return context.l10n.mar;
      case Countries.mau:
        return context.l10n.mus;
      case Countries.mrt:
        return context.l10n.mrt;
      case Countries.mex:
        return context.l10n.mex;
      case Countries.fsm:
        return context.l10n.fsm;
      case Countries.mda:
        return context.l10n.mda;
      case Countries.mco:
        return context.l10n.mco;
      case Countries.mong:
        return context.l10n.mng;
      case Countries.mne:
        return context.l10n.mne;
      case Countries.moz:
        return context.l10n.moz;
      case Countries.nam:
        return context.l10n.nam;
      case Countries.nru:
        return context.l10n.nru;
      case Countries.npa:
        return context.l10n.npl;
      case Countries.nca:
        return context.l10n.nic;
      case Countries.ner:
        return context.l10n.ner;
      case Countries.nga:
        return context.l10n.nga;
      case Countries.nor:
        return context.l10n.nor;
      case Countries.nzl:
        return context.l10n.nzl;
      case Countries.omn:
        return context.l10n.omn;
      case Countries.nld:
        return context.l10n.nld;
      case Countries.pak:
        return context.l10n.pak;
      case Countries.plw:
        return context.l10n.plw;
      case Countries.pan:
        return context.l10n.pan;
      case Countries.png:
        return context.l10n.png;
      case Countries.pry:
        return context.l10n.pry;
      case Countries.per:
        return context.l10n.per;
      case Countries.pol:
        return context.l10n.pol;
      case Countries.prt:
        return context.l10n.prt;
      case Countries.gbr:
        return context.l10n.gbr;
      case Countries.rca:
        return context.l10n.caf;
      case Countries.cze:
        return context.l10n.cze;
      case Countries.con:
        return context.l10n.cog;
      case Countries.dom:
        return context.l10n.dom;
      case Countries.rum:
        return context.l10n.rou;
      case Countries.rwa:
        return context.l10n.rwa;
      case Countries.kna:
        return context.l10n.kna;
      case Countries.lca:
        return context.l10n.lca;
      case Countries.vct:
        return context.l10n.vct;
      case Countries.wsm:
        return context.l10n.wsm;
      case Countries.smr:
        return context.l10n.smr;
      case Countries.stp:
        return context.l10n.stp;
      case Countries.sen:
        return context.l10n.sen;
      case Countries.srb:
        return context.l10n.srb;
      case Countries.sey:
        return context.l10n.syc;
      case Countries.sle:
        return context.l10n.sle;
      case Countries.sgp:
        return context.l10n.sgp;
      case Countries.sir:
        return context.l10n.syr;
      case Countries.som:
        return context.l10n.som;
      case Countries.lka:
        return context.l10n.lka;
      case Countries.swz:
        return context.l10n.swz;
      case Countries.zaf:
        return context.l10n.zaf;
      case Countries.sds:
        return context.l10n.ssd;
      case Countries.swe:
        return context.l10n.swe;
      case Countries.sui:
        return context.l10n.che;
      case Countries.sur:
        return context.l10n.sur;
      case Countries.thai:
        return context.l10n.tha;
      case Countries.tza:
        return context.l10n.tza;
      case Countries.tjk:
        return context.l10n.tjk;
      case Countries.tkm:
        return context.l10n.tkm;
      case Countries.tog:
        return context.l10n.tgo;
      case Countries.ton:
        return context.l10n.ton;
      case Countries.tto:
        return context.l10n.tto;
      case Countries.tun:
        return context.l10n.tun;
      case Countries.tur:
        return context.l10n.tur;
      case Countries.ukr:
        return context.l10n.ukr;
      case Countries.uga:
        return context.l10n.uga;
      case Countries.uzb:
        return context.l10n.uzb;
      case Countries.vut:
        return context.l10n.vut;
      case Countries.ven:
        return context.l10n.ven;
      case Countries.vnm:
        return context.l10n.vnm;
      case Countries.yem:
        return context.l10n.yem;
      case Countries.dji:
        return context.l10n.dji;
      case Countries.zmb:
        return context.l10n.zmb;
      case Countries.zwe:
        return context.l10n.zwe;
      case Countries.tls:
        return context.l10n.tls;
      default:
        return '';
    }
  }
}
