name: auth
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.0

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^5.6.0
  dartz: ^0.10.1
  dio: ^5.1.2
  errors:
    path: ../errors
  firebase_auth: ^5.3.4
  firebase_core: ^3.9.0
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  google_sign_in: ^6.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  rxdart: ^0.28.0
  firebase_storage: ^12.3.7

dev_dependencies:
  build_runner: ^2.3.0
  flutter_test:
    sdk: flutter
  freezed: ^2.2.0
  json_serializable: ^6.5.4
  mocktail: ^1.0.4
  very_good_analysis: ^7.0.0
