// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSkISICNq0Caq6Ex2zjqqHhbUwdFnGqH8',
    appId: '1:207314336522:web:b69e118c95cb8f49f998f3',
    messagingSenderId: '207314336522',
    projectId: 'maasters-72b3a',
    authDomain: 'maasters-72b3a.firebaseapp.com',
    storageBucket: 'maasters-72b3a.appspot.com',
    measurementId: 'G-DJXZPJ5PEH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC03MF3rR0IvOuEsOZBpkQDDnmZXUIk3aY',
    appId: '1:207314336522:android:8b51717d74e275cdf998f3',
    messagingSenderId: '207314336522',
    projectId: 'maasters-72b3a',
    storageBucket: 'maasters-72b3a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNlLnyDSCsSa3TSKUhRbcSwIkYnBmqQ1I',
    appId: '1:207314336522:ios:465b50f21f7d9141f998f3',
    messagingSenderId: '207314336522',
    projectId: 'maasters-72b3a',
    storageBucket: 'maasters-72b3a.appspot.com',
    iosClientId: '207314336522-8tebpin6sbedj1eco7o7ssmkdnjg5pum.apps.googleusercontent.com',
    iosBundleId: 'com.example.verygoodcore.maasters',
  );
}
