// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_stg.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8JsTf1weRYltiYmjiwJcK_vr5cr-E-EM',
    appId: '1:509674632325:web:ddf7f71e281578130825ec',
    messagingSenderId: '509674632325',
    projectId: 'maasters-stg',
    authDomain: 'maasters-stg.firebaseapp.com',
    storageBucket: 'maasters-stg.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqoF3aNf2Nb1fUZmLBZuv9ptD_ZALAqKw',
    appId: '1:509674632325:android:f6997b52f2ee17440825ec',
    messagingSenderId: '509674632325',
    projectId: 'maasters-stg',
    storageBucket: 'maasters-stg.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuA1WG-Ur5eVlsgB6R9fUqDcBt61rHEDY',
    appId: '1:509674632325:ios:f1e8af7c4df9546f0825ec',
    messagingSenderId: '509674632325',
    projectId: 'maasters-stg',
    storageBucket: 'maasters-stg.appspot.com',
    iosClientId: '509674632325-tt2bi1602o2ci4fh0e330jgaakjnlrqn.apps.googleusercontent.com',
    iosBundleId: 'com.example.verygoodcore.maasters.stg',
  );
}
