name: mentorships
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.0

dependencies:
  auth:
    path: ../auth
  cloud_firestore: ^5.6.0
  dartz: ^0.10.1
  errors:
    path: ../errors
  firebase_core: ^3.9.0
  flutter:
    sdk: flutter
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^7.0.0
