name: mentorships
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.0

dependencies:
  auth:
    path: ../auth
  flutter:
    sdk: flutter
  cloud_firestore: ^4.7.1
  dartz: ^0.10.1
  errors:
    path: ../errors
  firebase_core: ^2.4.0
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0
